version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.0.0
  serverless: circleci/serverless-framework@1.0.1

jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - serverless/setup:
          app-name: japan-grid-carbon-api
          provider: google
      - run:
          command: ./deployAll.sh
          name: deploy

workflows:
  build-and-deploy:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: myContext
      - deploy:
          requires:
            - gcp-cli/install_and_initialize_cli
