version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.4
  serverless: circleci/serverless-framework@1.0.1

jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            cd cloud_functions
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: deploy
          command: |
            cd cloud_functions
            gcloud functions set-iam-policy --region=us-central1 api policy.json
            sls deploy

workflows:
  build-and-deploy:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: japan-grid-carbon-api
      - deploy:
          requires:
            - gcp-cli/install_and_initialize_cli
          filters:
            branches:
              only:
                - master
